networks:
  main:
    name: MiniTwit

services:
  
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - main
    ports:
      - "8888:80"
  
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - main
    ports:
      - "80:80"
    volumes:
      - ./tls/nginxConfiguration:/etc/nginx/conf.d/default.conf
      - certbot_webroot:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
        
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot_webroot:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    
  minitwitimage-e:
    image: ${DOCKER_USERNAME:-gartner1et}/minitwitimage-e
    container_name: minitwit
    networks:
      - main
    ports:
      - '5000:8080'
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
    depends_on:
      - grafana
      - prometheus
  
  prometheus:
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/prometheus
    image: prometheus_image
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - main


  grafana:
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/grafana
    image: grafana_image
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - main
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: { }
  certbot_webroot:
  letsencrypt: