networks:
  main:
    name: MiniTwit

services:
  
  minitwitimage-e:
    image: ${DOCKER_USERNAME:-user}/minitwitimage-e
    container_name: minitwit
    networks:
      - main
    ports:
      - '5000:8080'
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
    depends_on:
      - grafana
      - prometheus
  
  prometheus:
    image: ${DOCKER_USERNAME:-user}/prometheusimage
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - main


  grafana:
    image: ${DOCKER_USERNAME:-user}/grafanaimage
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - main
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: { }