FROM dhi.io/aspnetcore:8 AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001

FROM dhi.io/dotnet:8-sdk AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/MiniTwit.Web/MiniTwit.Web.csproj", "src/MiniTwit.Web/"]
COPY ["src/MiniTwit.Core/MiniTwit.Core.csproj", "src/MiniTwit.Core/"]
COPY ["src/MiniTwit.Infrastructure/MiniTwit.Infrastructure.csproj", "src/MiniTwit.Infrastructure/"]
RUN dotnet restore "src/MiniTwit.Web/MiniTwit.Web.csproj"
COPY . .
WORKDIR "/src/src/MiniTwit.Web"
RUN dotnet publish "./MiniTwit.Web.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false


FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MiniTwit.Web.dll"]
