using MiniTwit.Core.Interfaces;
using MiniTwit.Infrastructure.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

// PageModel generated by ChatGPT and modified

public class FollowModel : PageModel
{
    private readonly IAuthorService _authorService;
    private readonly UserManager<Author> _userManager;

    public FollowModel(IAuthorService authorService, UserManager<Author> userManager)
    {
        _authorService = authorService;
        _userManager = userManager;
    }

    //OnGet method for when a following/unfollowing-"button" is pressed
    public async Task<IActionResult> OnGetAsync(string target, bool undo, string? returnUrl)
    {
        var current = await _userManager.GetUserAsync(HttpContext.User);
        
        if (current == null) return Redirect(returnUrl ?? "/");

        if (undo)
            await _authorService.Unfollow(current.Name, target);
        else
            await _authorService.Follow(current.Name, target);

        return Redirect(returnUrl ?? "/");
    }
}