{
 "title": "Application Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU time used by the app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"itu-minitwit-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Requests Recieved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (http_requests_received_total{job=\"itu-minitwit-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_requests_received_total", "legendFormat": "{{page}}" }
   ]
  }
 ]
}