{
 "title": "Infrastructure Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"itu-minitwit-app\"}",
     "legendFormat": "RAM used in bytes"
    },
    {
     "expr": "dotnet_total_memory_bytes{job=\"itu-minitwit-app\"}",
     "legendFormat": "Memory allocated by .NET runtime"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"itu-minitwit-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"itu-minitwit-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}