# Almost exactly the same as the corresponding file in the exercise example for session6
apiVersion: 1

# Inspired by https://community.grafana.com/t/solved-datasource-provisioning-prometheus/6300
datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false
    "uid": ffgrs1bgeercwe # Might need to be changes upon new dashboard exports from Grafana
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
