name: Static Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Docker Linter: Hadolint
    - name: Lint Dockerfiles
      uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5
      with:
        dockerfile: Dockerfile-MiniTwit # Our dockerfile path

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # C# Formatter: CSharpier
    - name: Restore tools
      run: dotnet tool restore
    - name: Check Formatting
      run: dotnet csharpier check .

    # Initialize CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'

    # C# Linter: Roslyn (Strict Linting)
    - name: Restore dependencies
      run: dotnet restore
    - name: Roslyn Static Analysis
      run: dotnet build --no-restore -c Release /p:TreatWarningsAsErrors=true
    
    # CodeQL Analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
    
    