/*
 * Minitwit API
 *
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using MiniTwit.Core.DTO;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;
using MiniTwit.Core.Interfaces;
using MiniTwit.Infrastructure.Entities;
using MiniTwit.Web;

namespace Org.OpenAPITools.Controllers
{ 
    [Route("/api")]
    public class MinitwitApiController : Controller
    {
        private readonly ICheepService _cheepService;
        private readonly IAuthorService _authorService;
        private readonly ILogger<MinitwitApiController> _logger;
        //latest contains the id of the lastest successful request
        public int Latest;
        private readonly LatestService _latestService;
        private readonly UserManager<Author> _userManager;

        public MinitwitApiController(ICheepService cheepService, IAuthorService authorService, LatestService latestService, ILogger<MinitwitApiController> logger, UserManager<Author> userManager)
        {
            _cheepService = cheepService;
            _authorService = authorService;
            _latestService = latestService;
            _logger = logger;
            _userManager = userManager;
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get list of users followed by the given user.  - Query param &#x60;?no&#x3D;&#x60; limits result count. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [Authorize(AuthenticationSchemes = "Basic", Policy = "SimulatorOnly")]
        [HttpGet("fllws/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetFollow")]
        [SwaggerResponse(statusCode: 200, type: typeof(FollowsResponse), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult GetFollow([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {  
            _logger.LogInformation("called get follows for user {user}",username);
            // Update latest if provided
            _latestService.SetLatest(latest);

            var author = _authorService.GetAuthorByName(username).Result;
            if (author == null)
            {
                return StatusCode(404);
            }

            // Get following list (ensure correct types)
            IList<string> followingList = author.Following ?? new List<string>();

            // Apply limit if provided
            var limit = no ?? 100;
            followingList = followingList.Take(limit).ToList();

            var response = new FollowsResponse { Follows = followingList.ToList() };
            return StatusCode(200, response.ToJson());
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Returns the latest ID saved</remarks>
        /// <response code="200">Success</response>
        /// <response code="500">Internal Server Error</response>
        [HttpGet]
        [Route("latest")]
        [ValidateModelState]
        [SwaggerOperation("GetLatestValue")]
        [SwaggerResponse(statusCode: 200, type: typeof(LatestValue), description: "Success")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        public virtual IActionResult GetLatestValue()
        {
            _logger.LogInformation("called get latest value");
            try
            {
                var response = new LatestValue() {Latest = _latestService.GetLatest()};
                return StatusCode(200, response.ToJson());
            }
            catch (Exception e)
            {
                return StatusCode(500, new ErrorResponse
                {
                    Status = 500,
                    ErrorMsg = "Internal Server Error"
                }.ToJson());
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get recent messages.  - Filters out flagged messages - Returns a list of recent messages (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [Authorize(AuthenticationSchemes = "Basic",Policy = "SimulatorOnly")]
        [HttpGet("msgs")]
        [ValidateModelState]
        [SwaggerOperation("GetMessages")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Message>), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult GetMessages([FromHeader (Name = "Authorization")]string? authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {
            _logger.LogInformation("called get messages with amount {amount}",no ?? 100);
            
            _latestService.SetLatest(latest);

            bool hasNext;
            //get recent cheeps
            var cheeps = _cheepService.GetCheeps(out hasNext, null);
            var messages = cheeps.Take(no ?? 100).Select(c => new Message {Content = c.Text,User = c.AuthorName,PubDate = c.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")}.ToJson()).ToList();

            return StatusCode(200, messages);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get messages for a specific user.  - Returns messages authored by the specified user - Filtered by unflagged - Returns a list of recent messages for the user (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [Authorize(AuthenticationSchemes = "Basic",Policy = "SimulatorOnly")]
        [HttpGet("msgs/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetMessagesPerUser")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Message>), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult GetMessagesPerUser([FromHeader (Name = "Authorization")][Required] string authorization, [FromRoute][Required] string username, [FromQuery] int? latest, [FromQuery] int? no)
        {
            _logger.LogInformation("called get messages per user with username {username} and amount {amount}",username, no ?? 100);
            _latestService.SetLatest(latest);
            if (_authorService.GetAuthorByName(username).Result == null)
            {
                return NotFound();
            }
               
            bool hasNext;
            //get recent cheeps
            var cheeps = _cheepService.GetCheepsFromAuthor(username,out hasNext, null);
            var messages = cheeps.Take(no ?? 100).Select(c => new Message {Content = c.Text,User = c.AuthorName,PubDate = c.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")}.ToJson()).ToList();

            return StatusCode(200, messages);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Follow or unfollow a user on behalf of &#x60;username&#x60;.  - Body must contain either &#x60;follow: &lt;user&gt;&#x60; or &#x60;unfollow: &lt;user&gt;&#x60;</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [Authorize(AuthenticationSchemes = "Basic",Policy = "SimulatorOnly")]
        [HttpPost("fllws/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostFollow")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult PostFollow([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromBody]FollowAction payload, [FromQuery (Name = "latest")]int? latest)
        {
            _logger.LogInformation("called fllws post as {user} who wants to {fllws}", username, payload);
            _latestService.SetLatest(latest);

            // Get the author by username
            var author = _authorService.GetAuthorByName(username).Result;
            if (author == null)
            {
                return StatusCode(404);
            }
            if ((string.IsNullOrEmpty(payload.Follow) && string.IsNullOrEmpty(payload.Unfollow)) ||
                (!string.IsNullOrEmpty(payload.Follow) && !string.IsNullOrEmpty(payload.Unfollow)))
            {
                return BadRequest(new ErrorResponse { Status = 400, ErrorMsg = "Exactly one of 'follow' or 'unfollow' must be provided"}.ToJson());
            }
            // Handle follow/unfollow action
            if (!string.IsNullOrEmpty(payload.Follow))
            {
                _authorService.Follow(username, payload.Follow).Wait();
            }
            else if (!string.IsNullOrEmpty(payload.Unfollow))
            {
                _authorService.Unfollow(username, payload.Unfollow).Wait();
            }

            return StatusCode(204);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Post a new message as a specific user.  - Message must include &#x60;content&#x60; in the body - Stored with timestamp and &#x60;flagged&#x3D;0&#x60; - Returns empty body on success - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [Authorize(AuthenticationSchemes = "Basic",Policy = "SimulatorOnly")]
        [HttpPost("msgs/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostMessagesPerUser")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult PostMessagesPerUser([FromHeader (Name = "Authorization")][Required()]string authorization, [FromRoute][Required] string username, [FromQuery] int? latest, [FromBody]PostMessage payload)
        {
            _logger.LogInformation("called msgs post with {user} and content {content}",username, payload.Content);
            _latestService.SetLatest(latest);
            var author =  _authorService.GetAuthorByName(username).Result;
            if (author == null)
            {
                return StatusCode(404);
            }
            var cheep = new CheepDTO() { AuthorId = author.Id,Text = payload.Content,CreatedAt = DateTime.UtcNow};
            
            _cheepService.CreateCheepFromDTO(cheep);

            return StatusCode(204);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Register a new user. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="400">Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken</response>
        [HttpPost("register")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostRegister")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken")]
        public virtual async Task<IActionResult> PostRegister([FromBody]RegisterRequest payload,  [FromQuery] int? latest)
        {
            _logger.LogInformation("called register with payload {payload}",payload);
            _latestService.SetLatest(latest);
            var user = CreateUser();

            user.UserName = payload.Email;
            user.Email = payload.Email;
            user.Name = payload.Username;
            user.Following = new List<string>();
            var result = await _userManager.CreateAsync(user, payload.Pwd);
            _logger.LogInformation("{} and errors {}",result.Succeeded, result.Errors.FirstOrDefault()?.Description);
            if (result.Succeeded)
            {
                _logger.LogInformation("added author {}", _authorService.GetAuthorByName(payload.Username).Result);
                return StatusCode(204);
            }

            return StatusCode(400, new ErrorResponse{Status = 400, ErrorMsg = "Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken"}.ToJson());
        }
        private Author CreateUser()
        {
            try
            {
                return Activator.CreateInstance<Author>();
            }
            catch
            {
                throw new InvalidOperationException($"Can't create an instance of '{nameof(Author)}'. " +
                                                    $"Ensure that '{nameof(Author)}' is not an abstract class and has a parameterless constructor, or alternatively " +
                                                    $"override the register page in /Areas/Identity/Pages/Account/Register.cshtml");
            }
        }
    }
}
